version: "3.1"

services:
  apache:
    build:
      context: ./apache-php
      dockerfile: Dockerfile
    volumes:
      - ./src:/var/www/html
    ports:
      - 5555:80

  db:
    image: mariadb:10.6.4
    restart: always
    environment:
      - MYSQL_DATABASE=hetic_backend
      - MYSQL_ROOT_PASSWORD=TEST
      - MYSQL_USER=test
      - MYSQL_PASSWORD=test

  phpmyadmin:
    image: phpmyadmin
    ports:
      - 8001:80
    restart: always
    environment:
      - PMA_ARBITRARY=1
